import com.shewetai.server.processor.CommandLineProcessor;

import java.io.File;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    private static String srcDir;
    private static String clientDir;
    private static String serverDir;

    public static void main(String[] args) {
        System.setProperty("jaxb", "com.sun.xml.bind.v2.bytecode.ClassTailor.noOptimize");
        if(checkArguments(args)){
            if(pathIsValid("Source Dir", srcDir) &&
                    pathIsValid("Client Dir", clientDir) &&
                    pathIsValid("Server Dir", serverDir)){
                new CommandLineProcessor(srcDir, clientDir, serverDir).process();
            }
        }
    }

    private static boolean checkArguments(String[] args) {
        if(args.length != 6){
            System.out.println("Arguments are not provided properly. Please follow the following format:");
            System.out.println("-src /path/to/src/files -clientDir /path/to/client/output/dir -serverDir /path/to/server/dir");
            return false;
        } else {
            srcDir = args[1];
            clientDir = args[3];
            serverDir = args[5];
            return true;
        }
    }

    private static boolean pathIsValid(String src, String path) {
        File f = new File(path);
        if(!f.isDirectory()){
            System.out.println("Invalid Directory path for: " + src + " " + path);
            return false;
        }
        return true;
    }

}
